package com.aran.dao;

import com.aran.model.AdminDepartment;
import com.aran.model.AdminDepartmentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface AdminDepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_department
     *
     * @mbg.generated
     */
    long countByExample(AdminDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_department
     *
     * @mbg.generated
     */
    int deleteByExample(AdminDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_department
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_department
     *
     * @mbg.generated
     */
    int insert(AdminDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_department
     *
     * @mbg.generated
     */
    int insertSelective(AdminDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_department
     *
     * @mbg.generated
     */
    List<AdminDepartment> selectByExample(AdminDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_department
     *
     * @mbg.generated
     */
    AdminDepartment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_department
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AdminDepartment record, @Param("example") AdminDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_department
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AdminDepartment record, @Param("example") AdminDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_department
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AdminDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_department
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AdminDepartment record);
}