package com.aran.model;

public class AdminDepartment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_department.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_department.department_name
     *
     * @mbg.generated
     */
    private String departmentName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_department.id
     *
     * @return the value of admin_department.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_department.id
     *
     * @param id the value for admin_department.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_department.department_name
     *
     * @return the value of admin_department.department_name
     *
     * @mbg.generated
     */
    public String getDepartmentName() {
        return departmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_department.department_name
     *
     * @param departmentName the value for admin_department.department_name
     *
     * @mbg.generated
     */
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName == null ? null : departmentName.trim();
    }
}